name: dry-run test

on: [push, pull_request]

jobs:
  test:
    name: dry-run test
    runs-on: ubuntu-18.04
    env:
      KUBECTL_STORAGEOS: /usr/local/bin/kubectl-storageos
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.16'
      - name: Install kubectl-storageos
        run: |
          make _build-pre
          sudo cp bin/kubectl-storageos $KUBECTL_STORAGEOS
      - name: Determine latest version
        run: |
          echo "STOS_VERSION=$(curl -s https://api.github.com/repos/storageos/operator/releases/latest | grep tag_name | head -1 | cut -d'"' -f4 | tr -d v)" >> $GITHUB_ENV
          echo "ETCD_OPERATOR_VERSION=$(curl -s https://api.github.com/repos/storageos/etcd-cluster-operator/releases/latest | grep tag_name | head -1 | cut -d'"' -f4 | tr -d v)" >> $GITHUB_ENV

      - name: Run dry-run-test.sh
        run: |
          cd e2e/tests/dry-run
          sudo STOS_VERSION=$STOS_VERSION ETCD_OPERATOR_VERSION=$ETCD_OPERATOR_VERSION ./dry-run-test.sh
