name: kuttl e2e test 1.20

on: [push, pull_request]

jobs:
  test:
    name: kuttl e2e test 1.20
    runs-on: ubuntu-18.04
    env:
      KUTTL: /usr/local/bin/kubectl-kuttl
      KUBECTL_STORAGEOS: /usr/local/bin/kubectl-storageos
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.16'
      - name: Install kuttl
        run: |
          sudo curl -Lo $KUTTL https://github.com/kudobuilder/kuttl/releases/download/v0.11.1/kubectl-kuttl_0.11.1_linux_x86_64
          sudo chmod +x $KUTTL
      - name: Install kubectl-storageos
        run: |
          make _build-pre
          sudo cp bin/kubectl-storageos $KUBECTL_STORAGEOS
      - name: Run kuttl installer 1.20
        run: sudo kubectl-kuttl test --config e2e/kuttl/kubectl-storageos-installer-1.20.yaml
      - name: Run kuttl upgrade 1.20
        run: sudo kubectl-kuttl test --config e2e/kuttl/kubectl-storageos-upgrade-1.20.yaml
      - name: Run kuttl installer 1.20
        run: sudo kubectl-kuttl test --config e2e/kuttl/kubectl-storageos-dry-run-1.20.yaml

