name: kuttl e2e test 1.21

on: [push, pull_request]

jobs:
  test:
    name: e2e test
    runs-on: ubuntu-18.04
    env:
      KUTTL: /usr/local/bin/kubectl-kuttl
      KUBECTL_STORAGEOS: /usr/local/bin/kubectl-storageos
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.16'
      - name: Install kuttl
        run: |
          sudo curl -Lo $KUTTL https://github.com/kudobuilder/kuttl/releases/download/v0.11.1/kubectl-kuttl_0.11.1_linux_x86_64
          sudo chmod +x $KUTTL
      - name: Install kubectl-storageos
        run: |
          make _build-pre
          sudo cp bin/kubectl-storageos $KUBECTL_STORAGEOS
      - name: Run kuttl
        run: sudo kubectl-kuttl test --config tests/e2e/kuttl-test.yaml --kind-config tests/e2e/versions/kind-config-1.21.yaml
